//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guardian_admins")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub two_fa_secret: Option<String>,
    pub is_super_admin: Option<bool>,
    pub status: Option<i16>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub login_attempts: Option<i32>,
    pub locked_until: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::admin_roles::Entity")]
    AdminRoles,
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::admin_roles::Relation::Role.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::admin_roles::Relation::Admin.def().rev())
    }
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
