//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod admin_roles;
pub mod admins;
pub mod audit_logs;
pub mod links;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod token_blacklist;
