//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::admin_roles::Entity as AdminRoles;
pub use super::admins::Entity as Admins;
pub use super::audit_logs::Entity as AuditLogs;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::token_blacklist::Entity as TokenBlacklist;
